### ISSUE TITLE
PhoneValidator class requires  "( )" but is not possible if the keyboard type is set to UIKeyboardType.numberPad

### ISSUE THREAD

**Issue by iminier** [Alberto-Vega/ValidateableTextField#7]
When using the text field to get a phone number one should set the field to UIKeyboardType.numberPad right? The number pad would make entering a phone number the easiest option for the user. If not the user must change the keyboard from apples qwerty keyboard to apples numbers and symbols keyboard which would be more prone to error by the user when entering a number. 

I would suggest removing the need for the ( ) around the area code as entering these symbols into the text field would not be possible for the user unless they copy paste, in which case the entry would fail as those symbols would not be part of the requirement anymore. 

Edit: Upon further exploration, one should use UIKeyboardType.phonePad which would solve the problem of verifying international numbers. 

Your thoughts?

**Comment by Alberto-Vega** [comment]
Hi @iminier I agree. I like using code that adds the parenthesis emulating the iPhone Contacts app. This just so the user can see the number in a more readable format. [like this](https://stackoverflow.com/questions/1246439/uitextfield-for-phone-number). But I agree that we can then strip the parenthesis from the number before the validation and then do whatever you want to do with the number.

**Comment by Alberto-Vega** [comment]
Included the functionality that adds the parentheses to the project
